import React, { useMemo } from "react";

const NetPayableByFirm = ({ payroll = [] }) => {
  // =========================================================
  // BUILD FIRM-WISE NET PAYABLE DATA
  // =========================================================

  const data = useMemo(() => {
    const firmSummary = {};

    payroll.forEach((record) => {
      const firm = record.firm || "UNKNOWN";

      if (!firmSummary[firm]) {
        firmSummary[firm] = {
          firm,
          employees: new Set(),
          netPayable: 0,
        };
      }

      /*
        Use employeeId to count unique employees.

        This is safer than simply counting payroll rows.
      */
      if (record.employeeId) {
        firmSummary[firm].employees.add(record.employeeId);
      }

      /*
        netSalary is already generated by the payroll engine.

        We are only reading it here.
        No payroll calculation happens in this component.
      */
      firmSummary[firm].netPayable += Number(record.netSalary || 0);
    });

    return Object.values(firmSummary)
      .map((item) => ({
        firm: item.firm,
        employees: item.employees.size,
        netPayable: item.netPayable,
      }))
      .sort((a, b) => b.netPayable - a.netPayable);
  }, [payroll]);

  // =========================================================
  // TOTAL NET PAYABLE
  // =========================================================

  const totalNetPayable = useMemo(() => {
    return data.reduce((total, item) => total + item.netPayable, 0);
  }, [data]);

  // =========================================================
  // FORMATTERS
  // =========================================================

  const formatCurrency = (value) => {
    return `₹${Number(value || 0).toLocaleString("en-IN", {
      maximumFractionDigits: 0,
    })}`;
  };

  const formatPercentage = (value) => {
    return Number(value || 0).toLocaleString("en-IN", {
      maximumFractionDigits: 1,
    });
  };

  // =========================================================
  // RENDER
  // =========================================================

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      {/* =====================================================
          HEADER
      ====================================================== */}

      <div className="mb-6">
        <h2 className="text-base font-semibold text-slate-800">
          Net Payable by Firm
        </h2>

        <p className="mt-1 text-sm text-slate-500">
          Monthly salary payable across company firms.
        </p>
      </div>

      {/* =====================================================
          FIRM BARS
      ====================================================== */}

      {data.length > 0 ? (
        <div className="space-y-5">
          {data.map((item) => {
            const percentage =
              totalNetPayable > 0
                ? (item.netPayable / totalNetPayable) * 100
                : 0;

            return (
              <div key={item.firm}>
                {/* Firm Information */}

                <div className="mb-2 flex items-center justify-between gap-4">
                  <div className="min-w-0">
                    <p className="text-sm font-medium text-slate-800">
                      {item.firm}
                    </p>

                    <p className="text-xs text-slate-500">
                      {item.employees.toLocaleString("en-IN")} employees
                    </p>
                  </div>

                  <div className="shrink-0 text-right">
                    <p className="text-sm font-semibold text-slate-800">
                      {formatCurrency(item.netPayable)}
                    </p>

                    <p className="text-xs text-slate-500">
                      {formatPercentage(percentage)}% of total
                    </p>
                  </div>
                </div>

                {/* Horizontal Bar */}

                <div className="h-3 overflow-hidden rounded-full bg-slate-100">
                  <div
                    className="h-full rounded-full bg-emerald-500 transition-all duration-500"
                    style={{
                      width: `${percentage}%`,
                    }}
                  />
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="py-10 text-center">
          <p className="text-sm text-slate-500">No payroll data available.</p>
        </div>
      )}

      {/* =====================================================
          TOTAL
      ====================================================== */}

      {data.length > 0 && (
        <div className="mt-6 flex items-center justify-between border-t border-slate-200 pt-4">
          <span className="text-sm font-medium text-slate-600">
            Total Net Payable
          </span>

          <span className="text-lg font-bold text-emerald-600">
            {formatCurrency(totalNetPayable)}
          </span>
        </div>
      )}
    </div>
  );
};

export default NetPayableByFirm;
